name: "acs_ygh_occupied_households_lacking_kitchen"
tag: "acs"
min_year: 2009
max_year: 2017
acs_table:
    id: "B25052"
    value_label: "occupied_households"
    dimension_labels: [
        "kitchen_facilities",
    ]
    columns:
        002E: "CompleteKitchenFacilities"
        003E: "LackingCompleteKitchenFacilities"


calc_percent: true
