name: "acs_ygh_health_care_coverage_overall"
tag: "acs"
min_year: 2012
max_year: 2017
acs_table:
    id: "B27010"
    value_label: "health_care_coverage_population"
    dimension_labels: [
        "age",
        "health_coverage",
    ]
    columns:
        004E: "Under18Years_WithOneTypeOfHealthInsuranceCoverage-WithEmployer-basedHealthInsuranceOnly"
        005E: "Under18Years_WithOneTypeOfHealthInsuranceCoverage-WithDirect-purchaseHealthInsuranceOnly"
        006E: "Under18Years_WithOneTypeOfHealthInsuranceCoverage-WithMedicareCoverageOnly"
        007E: "Under18Years_WithOneTypeOfHealthInsuranceCoverage-WithMedicaid/means-testedPublicCoverageOnly"
        008E: "Under18Years_WithOneTypeOfHealthInsuranceCoverage-WithTRICARE/militaryHealthCoverageOnly"
        009E: "Under18Years_WithOneTypeOfHealthInsuranceCoverage-WithVAHealthCareOnly"
        011E: "Under18Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithEmployer-basedAndDirect-purchaseCoverage"
        012E: "Under18Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithEmployer-basedAndMedicareCoverage"
        013E: "Under18Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithMedicareAndMedicaid/means-testedPublicCoverage"
        014E: "Under18Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherPrivateOnlyCombinations"
        015E: "Under18Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherPublicOnlyCombinations"
        016E: "Under18Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherCoverageCombinations"
        017E: "Under18Years_NoHealthInsuranceCoverage"
        020E: "18To34Years_WithOneTypeOfHealthInsuranceCoverage-WithEmployer-basedHealthInsuranceOnly"
        021E: "18To34Years_WithOneTypeOfHealthInsuranceCoverage-WithDirect-purchaseHealthInsuranceOnly"
        022E: "18To34Years_WithOneTypeOfHealthInsuranceCoverage-WithMedicareCoverageOnly"
        023E: "18To34Years_WithOneTypeOfHealthInsuranceCoverage-WithMedicaid/means-testedPublicCoverageOnly"
        024E: "18To34Years_WithOneTypeOfHealthInsuranceCoverage-WithTRICARE/militaryHealthCoverageOnly"
        025E: "18To34Years_WithOneTypeOfHealthInsuranceCoverage-WithVAHealthCareOnly"
        027E: "18To34Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithEmployer-basedAndDirect-purchaseCoverage"
        028E: "18To34Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithEmployer-basedAndMedicareCoverage"
        029E: "18To34Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithMedicareAndMedicaid/means-testedPublicCoverage"
        030E: "18To34Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherPrivateOnlyCombinations"
        031E: "18To34Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherPublicOnlyCombinations"
        032E: "18To34Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherCoverageCombinations"
        033E: "18To34Years_NoHealthInsuranceCoverage"
        036E: "35To64Years_WithOneTypeOfHealthInsuranceCoverage-WithEmployer-basedHealthInsuranceOnly"
        037E: "35To64Years_WithOneTypeOfHealthInsuranceCoverage-WithDirect-purchaseHealthInsuranceOnly"
        038E: "35To64Years_WithOneTypeOfHealthInsuranceCoverage-WithMedicareCoverageOnly"
        039E: "35To64Years_WithOneTypeOfHealthInsuranceCoverage-WithMedicaid/means-testedPublicCoverageOnly"
        040E: "35To64Years_WithOneTypeOfHealthInsuranceCoverage-WithTRICARE/militaryHealthCoverageOnly"
        041E: "35To64Years_WithOneTypeOfHealthInsuranceCoverage-WithVAHealthCareOnly"
        043E: "35To64Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithEmployer-basedAndDirect-purchaseCoverage"
        044E: "35To64Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithEmployer-basedAndMedicareCoverage"
        045E: "35To64Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithDirect-purchaseAndMedicareCoverage"
        046E: "35To64Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithMedicareAndMedicaid/means-testedPublicCoverage"
        047E: "35To64Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherPrivateOnlyCombinations"
        048E: "35To64Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherPublicOnlyCombinations"
        049E: "35To64Years_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherCoverageCombinations"
        050E: "35To64Years_NoHealthInsuranceCoverage"
        053E: "65YearsAndOver_WithOneTypeOfHealthInsuranceCoverage-WithEmployer-basedHealthInsuranceOnly"
        054E: "65YearsAndOver_WithOneTypeOfHealthInsuranceCoverage-WithDirect-purchaseHealthInsuranceOnly"
        055E: "65YearsAndOver_WithOneTypeOfHealthInsuranceCoverage-WithMedicareCoverageOnly"
        056E: "65YearsAndOver_WithOneTypeOfHealthInsuranceCoverage-WithTRICARE/militaryHealthCoverageOnly"
        057E: "65YearsAndOver_WithOneTypeOfHealthInsuranceCoverage-WithVAHealthCareOnly"
        059E: "65YearsAndOver_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithEmployer-basedAndDirect-purchaseCoverage"
        060E: "65YearsAndOver_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithEmployer-basedAndMedicareCoverage"
        061E: "65YearsAndOver_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithDirect-purchaseAndMedicareCoverage"
        062E: "65YearsAndOver_WithTwoOrMoreTypesOfHealthInsuranceCoverage-WithMedicareAndMedicaid/means-testedPublicCoverage"
        063E: "65YearsAndOver_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherPrivateOnlyCombinations"
        064E: "65YearsAndOver_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherPublicOnlyCombinations"
        065E: "65YearsAndOver_WithTwoOrMoreTypesOfHealthInsuranceCoverage-OtherCoverageCombinations"
        066E: "65YearsAndOver_NoHealthInsuranceCoverage"


calc_percent: true
no_schema: true
