name: "acs_ygh_renters_with_gross_rent_30_percent_of_household_income_c"
tag: "acs"
min_year: 2012
max_year: 2017
acs_table:
    id: "C25074"
    value_label: "renters_population"
    dimension_labels: [
        "household_income",
        "gross_rent_percent_of_income",
    ]
    columns:
        003E: "LessThan$10,000_LessThan30.0Percent"
        004E: "LessThan$10,000_30.0PercentOrMore"
        005E: "LessThan$10,000_NotComputed"
        007E: "$10,000To$19,999_LessThan30.0Percent"
        008E: "$10,000To$19,999_30.0PercentOrMore"
        009E: "$10,000To$19,999_NotComputed"
        011E: "$20,000To$34,999_LessThan30.0Percent"
        012E: "$20,000To$34,999_30.0PercentOrMore"
        013E: "$20,000To$34,999_NotComputed"
        015E: "$35,000To$49,999_LessThan30.0Percent"
        016E: "$35,000To$49,999_30.0PercentOrMore"
        017E: "$35,000To$49,999_NotComputed"
        019E: "$50,000To$74,999_LessThan30.0Percent"
        020E: "$50,000To$74,999_30.0PercentOrMore"
        021E: "$50,000To$74,999_NotComputed"
        023E: "$75,000OrMore_LessThan30.0Percent"
        024E: "$75,000OrMore_30.0PercentOrMore"
        025E: "$75,000OrMore_NotComputed"


calc_percent: true
