name: "acs_ygf_place_of_birth_for_foreign_born"
tag: "acs"
min_year: 2015
max_year: 2017
acs_table:
    id: "B05006"
    value_label: "foreign_born_population"
    dimension_labels: [
        "place_of_birth::continent",
        "place_of_birth::subcontinent",
        "place_of_birth::region",
        "place_of_birth::country",
    ]
    columns:
        005E: "Europe_NorthernEurope_UnitedKingdom(inc.CrownDependencies)_UnitedKingdom,ExcludingEnglandAndScotland"
        006E: "Europe_NorthernEurope_UnitedKingdom(inc.CrownDependencies)_England"
        007E: "Europe_NorthernEurope_UnitedKingdom(inc.CrownDependencies)_Scotland"
        008E: "Europe_NorthernEurope_NorthernEurope_Ireland"
        009E: "Europe_NorthernEurope_NorthernEurope_Denmark"
        010E: "Europe_NorthernEurope_NorthernEurope_Norway"
        011E: "Europe_NorthernEurope_NorthernEurope_Sweden"
        012E: "Europe_NorthernEurope_OtherNorthernEurope"
        014E: "Europe_WesternEurope_WesternEurope_Austria"
        015E: "Europe_WesternEurope_WesternEurope_Belgium"
        016E: "Europe_WesternEurope_WesternEurope_France"
        017E: "Europe_WesternEurope_WesternEurope_Germany"
        018E: "Europe_WesternEurope_WesternEurope_Netherlands"
        019E: "Europe_WesternEurope_WesternEurope_Switzerland"
        020E: "Europe_WesternEurope_WesternEurope_OtherWesternEurope"
        022E: "Europe_SouthernEurope_SouthernEurope_Greece"
        023E: "Europe_SouthernEurope_SouthernEurope_Italy"
        024E: "Europe_SouthernEurope_SouthernEurope_Portugal"
        025E: "Europe_SouthernEurope_SouthernEurope_Portugal!!AzoresIslands"
        026E: "Europe_SouthernEurope_SouthernEurope_Spain"
        027E: "Europe_SouthernEurope_SouthernEurope_OtherSouthernEurope"
        029E: "Europe_EasternEurope_EasternEurope_Albania"
        030E: "Europe_EasternEurope_EasternEurope_Belarus"
        031E: "Europe_EasternEurope_EasternEurope_Bulgaria"
        032E: "Europe_EasternEurope_EasternEurope_Croatia"
        033E: "Europe_EasternEurope_EasternEurope_Czechoslovakia(includesCzechRepublicAndSlovakia)"
        034E: "Europe_EasternEurope_EasternEurope_Hungary"
        035E: "Europe_EasternEurope_EasternEurope_Latvia"
        036E: "Europe_EasternEurope_EasternEurope_Lithuania"
        037E: "Europe_EasternEurope_EasternEurope_Macedonia"
        038E: "Europe_EasternEurope_EasternEurope_Moldova"
        039E: "Europe_EasternEurope_EasternEurope_Poland"
        040E: "Europe_EasternEurope_EasternEurope_Romania"
        041E: "Europe_EasternEurope_EasternEurope_Russia"
        042E: "Europe_EasternEurope_EasternEurope_Ukraine"
        043E: "Europe_EasternEurope_EasternEurope_BosniaAndHerzegovina"
        044E: "Europe_EasternEurope_EasternEurope_Serbia"
        045E: "Europe_EasternEurope_EasternEurope_OtherEasternEurope"
        046E: "Europe_Europe_Europe_Europe,N.e.c."
        050E: "Asia_EasternAsia_EasternAsia_China_China,ExcludingHongKongAndTaiwan"
        051E: "Asia_EasternAsia_EasternAsia_China_HongKong"
        052E: "Asia_EasternAsia_EasternAsia_China_Taiwan"
        053E: "Asia_EasternAsia_EasternAsia_Japan"
        054E: "Asia_EasternAsia_EasternAsia_Korea"
        055E: "Asia_EasternAsia_EasternAsia_OtherEasternAsia"
        057E: "Asia_SouthCentralAsia_SouthCentralAsia_Afghanistan"
        058E: "Asia_SouthCentralAsia_SouthCentralAsia_Bangladesh"
        059E: "Asia_SouthCentralAsia_SouthCentralAsia_India"
        060E: "Asia_SouthCentralAsia_SouthCentralAsia_Iran"
        061E: "Asia_SouthCentralAsia_SouthCentralAsia_Kazakhstan"
        062E: "Asia_SouthCentralAsia_SouthCentralAsia_Nepal"
        063E: "Asia_SouthCentralAsia_SouthCentralAsia_Pakistan"
        064E: "Asia_SouthCentralAsia_SouthCentralAsia_SriLanka"
        065E: "Asia_SouthCentralAsia_SouthCentralAsia_Uzbekistan"
        066E: "Asia_SouthCentralAsia_SouthCentralAsia_OtherSouthCentralAsia"
        068E: "Asia_SouthEasternAsia_SouthEasternAsia_Cambodia"
        069E: "Asia_SouthEasternAsia_SouthEasternAsia_Indonesia"
        070E: "Asia_SouthEasternAsia_SouthEasternAsia_Laos"
        071E: "Asia_SouthEasternAsia_SouthEasternAsia_Malaysia"
        072E: "Asia_SouthEasternAsia_SouthEasternAsia_Burma"
        073E: "Asia_SouthEasternAsia_SouthEasternAsia_Philippines"
        074E: "Asia_SouthEasternAsia_SouthEasternAsia_Singapore"
        075E: "Asia_SouthEasternAsia_SouthEasternAsia_Thailand"
        076E: "Asia_SouthEasternAsia_SouthEasternAsia_Vietnam"
        077E: "Asia_SouthEasternAsia_SouthEasternAsia_OtherSouthEasternAsia"
        079E: "Asia_WesternAsia_WesternAsia_Iraq"
        080E: "Asia_WesternAsia_WesternAsia_Israel"
        081E: "Asia_WesternAsia_WesternAsia_Jordan"
        082E: "Asia_WesternAsia_WesternAsia_Kuwait"
        083E: "Asia_WesternAsia_WesternAsia_Lebanon"
        084E: "Asia_WesternAsia_WesternAsia_SaudiArabia"
        085E: "Asia_WesternAsia_WesternAsia_Syria"
        086E: "Asia_WesternAsia_WesternAsia_Yemen"
        087E: "Asia_WesternAsia_WesternAsia_Turkey"
        088E: "Asia_WesternAsia_WesternAsia_Armenia"
        089E: "Asia_WesternAsia_WesternAsia_OtherWesternAsia"
        090E: "Asia_Asia_Asia_Asia,n.e.c."
        093E: "Africa_EasternAfrica_EasternAfrica_Eritrea"
        094E: "Africa_EasternAfrica_EasternAfrica_Ethiopia"
        095E: "Africa_EasternAfrica_EasternAfrica_Kenya"
        096E: "Africa_EasternAfrica_EasternAfrica_Somalia"
        097E: "Africa_EasternAfrica_EasternAfrica_OtherEasternAfrica"
        099E: "Africa_MiddleAfrica_MiddleAfrica_Cameroon"
        100E: "Africa_MiddleAfrica_MiddleAfrica_OtherMiddleAfrica"
        102E: "Africa_NorthernAfrica_NorthernAfrica_Egypt"
        103E: "Africa_NorthernAfrica_NorthernAfrica_Morocco"
        104E: "Africa_NorthernAfrica_NorthernAfrica_Sudan"
        105E: "Africa_NorthernAfrica_NorthernAfrica_OtherNorthernAfrica"
        107E: "Africa_SouthernAfrica_SouthernAfrica_SouthAfrica"
        108E: "Africa_SouthernAfrica_SouthernAfrica_OtherSouthernAfrica"
        110E: "Africa_WesternAfrica_WesternAfrica_CaboVerde"
        111E: "Africa_WesternAfrica_WesternAfrica_Ghana"
        112E: "Africa_WesternAfrica_WesternAfrica_Liberia"
        113E: "Africa_WesternAfrica_WesternAfrica_Nigeria"
        114E: "Africa_WesternAfrica_WesternAfrica_SierraLeone"
        115E: "Africa_WesternAfrica_WesternAfrica_OtherWesternAfrica"
        116E: "Africa_Africa_Africa_Africa,N.e.c."
        119E: "Oceania_AustraliaAndNewZealandSubregion_AustraliaAndNewZealandSubregion_Australia"
        120E: "Oceania_AustraliaAndNewZealandSubregion_AustraliaAndNewZealandSubregion_OtherAustralianAndNewZealandSubregion"
        121E: "Oceania_Oceania_Oceania_Fiji"
        122E: "Oceania_Oceania_Oceania_Oceania,N.e.c."
        126E: "Americas_LatinAmerica_Caribbean_Bahamas"
        127E: "Americas_LatinAmerica_Caribbean_Barbados"
        128E: "Americas_LatinAmerica_Caribbean_Cuba"
        129E: "Americas_LatinAmerica_Caribbean_Dominica"
        130E: "Americas_LatinAmerica_Caribbean_DominicanRepublic"
        131E: "Americas_LatinAmerica_Caribbean_Grenada"
        132E: "Americas_LatinAmerica_Caribbean_Haiti"
        133E: "Americas_LatinAmerica_Caribbean_Jamaica"
        134E: "Americas_LatinAmerica_Caribbean_St.VincentAndTheGrenadines"
        135E: "Americas_LatinAmerica_Caribbean_TrinidadAndTobago"
        136E: "Americas_LatinAmerica_Caribbean_WestIndies"
        137E: "Americas_LatinAmerica_Caribbean_OtherCaribbean"
        139E: "Americas_LatinAmerica_CentralAmerica_Mexico"
        140E: "Americas_LatinAmerica_CentralAmerica_Belize"
        141E: "Americas_LatinAmerica_CentralAmerica_CostaRica"
        142E: "Americas_LatinAmerica_CentralAmerica_ElSalvador"
        143E: "Americas_LatinAmerica_CentralAmerica_Guatemala"
        144E: "Americas_LatinAmerica_CentralAmerica_Honduras"
        145E: "Americas_LatinAmerica_CentralAmerica_Nicaragua"
        146E: "Americas_LatinAmerica_CentralAmerica_Panama"
        147E: "Americas_LatinAmerica_CentralAmerica_OtherCentralAmerica"
        149E: "Americas_LatinAmerica_SouthAmerica_Argentina"
        150E: "Americas_LatinAmerica_SouthAmerica_Bolivia"
        151E: "Americas_LatinAmerica_SouthAmerica_Brazil"
        152E: "Americas_LatinAmerica_SouthAmerica_Chile"
        153E: "Americas_LatinAmerica_SouthAmerica_Colombia"
        154E: "Americas_LatinAmerica_SouthAmerica_Ecuador"
        155E: "Americas_LatinAmerica_SouthAmerica_Guyana"
        156E: "Americas_LatinAmerica_SouthAmerica_Peru"
        157E: "Americas_LatinAmerica_SouthAmerica_Uruguay"
        158E: "Americas_LatinAmerica_SouthAmerica_Venezuela"
        159E: "Americas_LatinAmerica_SouthAmerica_OtherSouthAmerica"
        161E: "Americas_NorthernAmerica_NorthernAmerica_Canada"
        162E: "Americas_NorthernAmerica_NorthernAmerica_OtherNorthernAmerica"


