name: "acs_ygt_means_of_transportation_to_work"
tag: "acs"
min_year: 2009
max_year: 2017
acs_table:
    id: "B08301"
    value_label: "means_of_work_transportation_population"
    dimension_labels: [
        "transportation::group",
        "transportation::subgroup",
        "transportation::transportation_means",
    ]
    columns:
        003E: "Car,Truck,OrVan_Car,Truck,OrVan_DroveAlone"
        005E: "Car,Truck,OrVan_Carpooled_In2-personCarpool"
        006E: "Car,Truck,OrVan_Carpooled_In3-personCarpool"
        007E: "Car,Truck,OrVan_Carpooled_In4-personCarpool"
        008E: "Car,Truck,OrVan_Carpooled_In5-Or6-personCarpool"
        009E: "Car,Truck,OrVan_Carpooled_In7-or-more-personCarpool"
        011E: "PublicTransportation(excludingTaxicab)_PublicTransportation(excludingTaxicab)_BusOrTrolleyBus"
        012E: "PublicTransportation(excludingTaxicab)_PublicTransportation(excludingTaxicab)_StreetcarOrTrolleyCar(carroPublicoInPuertoRico)"
        013E: "PublicTransportation(excludingTaxicab)_PublicTransportation(excludingTaxicab)_SubwayOrElevated"
        014E: "PublicTransportation(excludingTaxicab)_PublicTransportation(excludingTaxicab)_Railroad"
        015E: "PublicTransportation(excludingTaxicab)_PublicTransportation(excludingTaxicab)_Ferryboat"
        016E: "Taxicab_Taxicab_Taxicab"
        017E: "Motorcycle_Motorcycle_Motorcycle"
        018E: "Bicycle_Bicycle_Bicycle"
        019E: "Walked_Walked_Walked"
        020E: "OtherMeans_OtherMeans_OtherMeans"
        021E: "WorkedAtHome_WorkedAtHome_WorkedAtHome"

