name: "acs_ygl_language_spoken_at_home_by_english_ability"
tag: "acs"
min_year: 2015
max_year: 2015
acs_table:
    id: "B16001"
    value_label: "language_population"
    dimension_labels: [
        "language_spoken_at_home",
        "english_ability",
    ]
    columns:
        002E: "SpeakOnlyEnglish_SpeakEnglish\"veryWell\""
        004E: "SpanishOrSpanishCreole_SpeakEnglish\"veryWell\""
        005E: "SpanishOrSpanishCreole_SpeakEnglishLessThan\"veryWell\""
        007E: "French(incl.Patois,Cajun)_SpeakEnglish\"veryWell\""
        008E: "French(incl.Patois,Cajun)_SpeakEnglishLessThan\"veryWell\""
        010E: "FrenchCreole_SpeakEnglish\"veryWell\""
        011E: "FrenchCreole_SpeakEnglishLessThan\"veryWell\""
        013E: "Italian_SpeakEnglish\"veryWell\""
        014E: "Italian_SpeakEnglishLessThan\"veryWell\""
        016E: "PortugueseOrPortugueseCreole_SpeakEnglish\"veryWell\""
        017E: "PortugueseOrPortugueseCreole_SpeakEnglishLessThan\"veryWell\""
        019E: "German_SpeakEnglish\"veryWell\""
        020E: "German_SpeakEnglishLessThan\"veryWell\""
        022E: "Yiddish_SpeakEnglish\"veryWell\""
        023E: "Yiddish_SpeakEnglishLessThan\"veryWell\""
        025E: "OtherWestGermanicLanguages_SpeakEnglish\"veryWell\""
        026E: "OtherWestGermanicLanguages_SpeakEnglishLessThan\"veryWell\""
        028E: "ScandinavianLanguages_SpeakEnglish\"veryWell\""
        029E: "ScandinavianLanguages_SpeakEnglishLessThan\"veryWell\""
        031E: "Greek_SpeakEnglish\"veryWell\""
        032E: "Greek_SpeakEnglishLessThan\"veryWell\""
        034E: "Russian_SpeakEnglish\"veryWell\""
        035E: "Russian_SpeakEnglishLessThan\"veryWell\""
        037E: "Polish_SpeakEnglish\"veryWell\""
        038E: "Polish_SpeakEnglishLessThan\"veryWell\""
        040E: "Serbo-Croatian_SpeakEnglish\"veryWell\""
        041E: "Serbo-Croatian_SpeakEnglishLessThan\"veryWell\""
        043E: "OtherSlavicLanguages_SpeakEnglish\"veryWell\""
        044E: "OtherSlavicLanguages_SpeakEnglishLessThan\"veryWell\""
        046E: "Armenian_SpeakEnglish\"veryWell\""
        047E: "Armenian_SpeakEnglishLessThan\"veryWell\""
        049E: "Persian_SpeakEnglish\"veryWell\""
        050E: "Persian_SpeakEnglishLessThan\"veryWell\""
        052E: "Gujarati_SpeakEnglish\"veryWell\""
        053E: "Gujarati_SpeakEnglishLessThan\"veryWell\""
        055E: "Hindi_SpeakEnglish\"veryWell\""
        056E: "Hindi_SpeakEnglishLessThan\"veryWell\""
        058E: "Urdu_SpeakEnglish\"veryWell\""
        059E: "Urdu_SpeakEnglishLessThan\"veryWell\""
        061E: "OtherIndicLanguages_SpeakEnglish\"veryWell\""
        062E: "OtherIndicLanguages_SpeakEnglishLessThan\"veryWell\""
        064E: "OtherIndo-EuropeanLanguages_SpeakEnglish\"veryWell\""
        065E: "OtherIndo-EuropeanLanguages_SpeakEnglishLessThan\"veryWell\""
        067E: "Chinese_SpeakEnglish\"veryWell\""
        068E: "Chinese_SpeakEnglishLessThan\"veryWell\""
        070E: "Japanese_SpeakEnglish\"veryWell\""
        071E: "Japanese_SpeakEnglishLessThan\"veryWell\""
        073E: "Korean_SpeakEnglish\"veryWell\""
        074E: "Korean_SpeakEnglishLessThan\"veryWell\""
        076E: "Mon-Khmer,Cambodian_SpeakEnglish\"veryWell\""
        077E: "Mon-Khmer,Cambodian_SpeakEnglishLessThan\"veryWell\""
        079E: "Hmong_SpeakEnglish\"veryWell\""
        080E: "Hmong_SpeakEnglishLessThan\"veryWell\""
        082E: "Thai_SpeakEnglish\"veryWell\""
        083E: "Thai_SpeakEnglishLessThan\"veryWell\""
        085E: "Laotian_SpeakEnglish\"veryWell\""
        086E: "Laotian_SpeakEnglishLessThan\"veryWell\""
        088E: "Vietnamese_SpeakEnglish\"veryWell\""
        089E: "Vietnamese_SpeakEnglishLessThan\"veryWell\""
        091E: "OtherAsianLanguages_SpeakEnglish\"veryWell\""
        092E: "OtherAsianLanguages_SpeakEnglishLessThan\"veryWell\""
        094E: "Tagalog_SpeakEnglish\"veryWell\""
        095E: "Tagalog_SpeakEnglishLessThan\"veryWell\""
        097E: "OtherPacificIslandLanguages_SpeakEnglish\"veryWell\""
        098E: "OtherPacificIslandLanguages_SpeakEnglishLessThan\"veryWell\""
        100E: "Navajo_SpeakEnglish\"veryWell\""
        101E: "Navajo_SpeakEnglishLessThan\"veryWell\""
        103E: "OtherNativeNorthAmericanLanguages_SpeakEnglish\"veryWell\""
        104E: "OtherNativeNorthAmericanLanguages_SpeakEnglishLessThan\"veryWell\""
        106E: "Hungarian_SpeakEnglish\"veryWell\""
        107E: "Hungarian_SpeakEnglishLessThan\"veryWell\""
        109E: "Arabic_SpeakEnglish\"veryWell\""
        110E: "Arabic_SpeakEnglishLessThan\"veryWell\""
        112E: "Hebrew_SpeakEnglish\"veryWell\""
        113E: "Hebrew_SpeakEnglishLessThan\"veryWell\""
        115E: "AfricanLanguages_SpeakEnglish\"veryWell\""
        116E: "AfricanLanguages_SpeakEnglishLessThan\"veryWell\""
        118E: "OtherAndUnspecifiedLanguages_SpeakEnglish\"veryWell\""
        119E: "OtherAndUnspecifiedLanguages_SpeakEnglishLessThan\"veryWell\""

calc_rca: True
