name: "acs_ygl_language_spoken_at_home_by_english_ability_2016"
tag: "acs"
min_year: 2016
max_year: 2017
acs_table:
    id: "B16001"
    value_label: "language_population"
    dimension_labels: [
        "language_spoken_at_home",
        "english_ability",
    ]
    columns:
        002E: "SpeakOnlyEnglish_SpeakEnglish\"veryWell\""
        004E: "Spanish_SpeakEnglish\"veryWell\""
        005E: "Spanish_SpeakEnglishLessThan\"veryWell\""
        007E: "French(incl.Cajun)_SpeakEnglish\"veryWell\""
        008E: "French(incl.Cajun)_SpeakEnglishLessThan\"veryWell\""
        010E: "Haitian_SpeakEnglish\"veryWell\""
        011E: "Haitian_SpeakEnglishLessThan\"veryWell\""
        013E: "Italian_SpeakEnglish\"veryWell\""
        014E: "Italian_SpeakEnglishLessThan\"veryWell\""
        016E: "Portuguese_SpeakEnglish\"veryWell\""
        017E: "Portuguese_SpeakEnglishLessThan\"veryWell\""
        019E: "German_SpeakEnglish\"veryWell\""
        020E: "German_SpeakEnglishLessThan\"veryWell\""
        022E: "Yiddish,PennsylvaniaDutchOrOtherWestGermanicLanguages_SpeakEnglish\"veryWell\""
        023E: "Yiddish,PennsylvaniaDutchOrOtherWestGermanicLanguages_SpeakEnglishLessThan\"veryWell\""
        025E: "Greek_SpeakEnglish\"veryWell\""
        026E: "Greek_SpeakEnglishLessThan\"veryWell\""
        028E: "Russian_SpeakEnglish\"veryWell\""
        029E: "Russian_SpeakEnglishLessThan\"veryWell\""
        031E: "Polish_SpeakEnglish\"veryWell\""
        032E: "Polish_SpeakEnglishLessThan\"veryWell\""
        034E: "Serbo-Croatian_SpeakEnglish\"veryWell\""
        035E: "Serbo-Croatian_SpeakEnglishLessThan\"veryWell\""
        037E: "UkrainianOrOtherSlavicLanguages_SpeakEnglish\"veryWell\""
        038E: "UkrainianOrOtherSlavicLanguages_SpeakEnglishLessThan\"veryWell\""
        040E: "Armenian_SpeakEnglish\"veryWell\""
        041E: "Armenian_SpeakEnglishLessThan\"veryWell\""
        043E: "Persian(incl.Farsi,Dari)_SpeakEnglish\"veryWell\""
        044E: "Persian(incl.Farsi,Dari)_SpeakEnglishLessThan\"veryWell\""
        046E: "Gujarati_SpeakEnglish\"veryWell\""
        047E: "Gujarati_SpeakEnglishLessThan\"veryWell\""
        049E: "Hindi_SpeakEnglish\"veryWell\""
        050E: "Hindi_SpeakEnglishLessThan\"veryWell\""
        052E: "Urdu_SpeakEnglish\"veryWell\""
        053E: "Urdu_SpeakEnglishLessThan\"veryWell\""
        055E: "Punjabi_SpeakEnglish\"veryWell\""
        056E: "Punjabi_SpeakEnglishLessThan\"veryWell\""
        058E: "Bengali_SpeakEnglish\"veryWell\""
        059E: "Bengali_SpeakEnglishLessThan\"veryWell\""
        061E: "Nepali,Marathi,OrOtherIndicLanguages_SpeakEnglish\"veryWell\""
        062E: "Nepali,Marathi,OrOtherIndicLanguages_SpeakEnglishLessThan\"veryWell\""
        064E: "OtherIndo-EuropeanLanguages_SpeakEnglish\"veryWell\""
        065E: "OtherIndo-EuropeanLanguages_SpeakEnglishLessThan\"veryWell\""
        067E: "Telugu_SpeakEnglish\"veryWell\""
        068E: "Telugu_SpeakEnglishLessThan\"veryWell\""
        070E: "Tamil_SpeakEnglish\"veryWell\""
        071E: "Tamil_SpeakEnglishLessThan\"veryWell\""
        073E: "Malayalam,Kannada,OrOtherDravidianLanguages_SpeakEnglish\"veryWell\""
        074E: "Malayalam,Kannada,OrOtherDravidianLanguages_SpeakEnglishLessThan\"veryWell\""
        076E: "Chinese(incl.Mandarin,Cantonese)_SpeakEnglish\"veryWell\""
        077E: "Chinese(incl.Mandarin,Cantonese)_SpeakEnglishLessThan\"veryWell\""
        079E: "Japanese_SpeakEnglish\"veryWell\""
        080E: "Japanese_SpeakEnglishLessThan\"veryWell\""
        082E: "Korean_SpeakEnglish\"veryWell\""
        083E: "Korean_SpeakEnglishLessThan\"veryWell\""
        085E: "Hmong_SpeakEnglish\"veryWell\""
        086E: "Hmong_SpeakEnglishLessThan\"veryWell\""
        088E: "Vietnamese_SpeakEnglish\"veryWell\""
        089E: "Vietnamese_SpeakEnglishLessThan\"veryWell\""
        091E: "Khmer_SpeakEnglish\"veryWell\""
        092E: "Khmer_SpeakEnglishLessThan\"veryWell\""
        094E: "Thai,Lao,OrOtherTai-KadaiLanguages_SpeakEnglish\"veryWell\""
        095E: "Thai,Lao,OrOtherTai-KadaiLanguages_SpeakEnglishLessThan\"veryWell\""
        097E: "OtherLanguagesOfAsia_SpeakEnglish\"veryWell\""
        098E: "OtherLanguagesOfAsia_SpeakEnglishLessThan\"veryWell\""
        100E: "Tagalog(incl.Filipino)_SpeakEnglish\"veryWell\""
        101E: "Tagalog(incl.Filipino)_SpeakEnglishLessThan\"veryWell\""
        103E: "Ilocano,Samoan,Hawaiian,OrOtherAustronesianLanguages_SpeakEnglish\"veryWell\""
        104E: "Ilocano,Samoan,Hawaiian,OrOtherAustronesianLanguages_SpeakEnglishLessThan\"veryWell\""
        106E: "Arabic_SpeakEnglish\"veryWell\""
        107E: "Arabic_SpeakEnglishLessThan\"veryWell\""
        109E: "Hebrew_SpeakEnglish\"veryWell\""
        110E: "Hebrew_SpeakEnglishLessThan\"veryWell\""
        112E: "Amharic,Somali,OrOtherAfro-AsiaticLanguages_SpeakEnglish\"veryWell\""
        113E: "Amharic,Somali,OrOtherAfro-AsiaticLanguages_SpeakEnglishLessThan\"veryWell\""
        115E: "Yoruba,Twi,Igbo,OrOtherLanguagesOfWesternAfrica_SpeakEnglish\"veryWell\""
        116E: "Yoruba,Twi,Igbo,OrOtherLanguagesOfWesternAfrica_SpeakEnglishLessThan\"veryWell\""
        118E: "SwahiliOrOtherLanguagesOfCentral,Eastern,AndSouthernAfrica_SpeakEnglish\"veryWell\""
        119E: "SwahiliOrOtherLanguagesOfCentral,Eastern,AndSouthernAfrica_SpeakEnglishLessThan\"veryWell\""
        121E: "Navajo_SpeakEnglish\"veryWell\""
        122E: "Navajo_SpeakEnglishLessThan\"veryWell\""
        124E: "OtherNativeLanguagesOfNorthAmerica_SpeakEnglish\"veryWell\""
        125E: "OtherNativeLanguagesOfNorthAmerica_SpeakEnglishLessThan\"veryWell\""
        127E: "OtherAndUnspecifiedLanguages_SpeakEnglish\"veryWell\""
        128E: "OtherAndUnspecifiedLanguages_SpeakEnglishLessThan\"veryWell\""
 
calc_rca: True
