name: "acs_yg_gini"
acs_table:
    id: "B19083"
    value_label: "gini"
    columns:
        001E: "GiniIndex"

    # order matters, should be same as column labels
    dimension_labels: [
    ]

tag: "acs"



