name: "acs_ygi_industry_for_median_earnings"
tag: "acs"
min_year: 2012
max_year: 2017
acs_table:
    id: "B24031"
    value_label: "industry_median_earnings_dollars"
    dimension_labels: [
        "industry::group",
        "industry::subgroup",
    ]
    columns:
        003: "Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting"
        004: "Agriculture,Forestry,FishingAndHunting,AndMining_Mining,Quarrying,AndOilAndGasExtraction"
        005: "Construction_Construction"
        006: "Manufacturing_Manufacturing"
        007: "WholesaleTrade_WholesaleTrade"
        008: "RetailTrade_RetailTrade"
        010: "TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing"
        011: "TransportationAndWarehousing,AndUtilities_Utilities"
        012: "Information_Information"
        014: "FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance"
        015: "FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_RealEstateAndRentalAndLeasing"
        017: "Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndTechnicalServices"
        018: "Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_ManagementOfCompaniesAndEnterprises"
        019: "Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_AdministrativeAndSupportAndWasteManagementServices"
        021: "EducationalServices,AndHealthCareAndSocialAssistance_EducationalServices"
        022: "EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance"
        024: "Arts,Entertainment,AndRecreation,AndAccommodationsAndFoodServices_Arts,Entertainment,AndRecreation"
        025: "Arts,Entertainment,AndRecreation,AndAccommodationsAndFoodServices_AccommodationAndFoodServices"
        026: "OtherServicesExceptPublicAdministration_OtherServicesExceptPublicAdministration"
        027: "PublicAdministration_PublicAdministration"


