acs_table:
  columns: {004E: 'Male_Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting',
    005E: 'Male_Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting,AndMining_Mining,Quarrying,AndOilAndGasExtraction',
    006E: Male_Construction_Construction_Construction, 008E: Male_Manufacturing_Manufacturing_Food,
    009E: Male_Manufacturing_Manufacturing_BeverageAndTobaccoProducts, 010E: Male_Manufacturing_Manufacturing_TextileMillsAndTextileProducts,
    011E: Male_Manufacturing_Manufacturing_Apparel, 012E: Male_Manufacturing_Manufacturing_LeatherAndAlliedProducts,
    013E: Male_Manufacturing_Manufacturing_WoodProducts, 014E: Male_Manufacturing_Manufacturing_Paper,
    015E: Male_Manufacturing_Manufacturing_PrintingAndRelatedSupportActivities, 016E: Male_Manufacturing_Manufacturing_PetroleumAndCoalProducts,
    017E: Male_Manufacturing_Manufacturing_Chemicals, 018E: Male_Manufacturing_Manufacturing_PlasticsAndRubberProducts,
    019E: Male_Manufacturing_Manufacturing_NonmetallicMineralProducts, 020E: Male_Manufacturing_Manufacturing_MetalAndMetalProducts,
    021E: Male_Manufacturing_Manufacturing_Machinery, 022E: Male_Manufacturing_Manufacturing_ComputerAndElectronicProducts,
    023E: 'Male_Manufacturing_Manufacturing_ElectricalEquipment,Appliances,AndComponents',
    024E: Male_Manufacturing_Manufacturing_TransportationEquipment, 025E: Male_Manufacturing_Manufacturing_FurnitureAndRelatedProductManufacturing,
    026E: Male_Manufacturing_Manufacturing_MiscellaneousManufacturing, 028E: Male_WholesaleTrade_WholesaleTrade_MotorVehicleAndMotorVehiclePartsAndSuppliesMerchantWholesalers,
    029E: Male_WholesaleTrade_WholesaleTrade_FurnitureAndHomeFurnishingMerchantWholesalers,
    030E: Male_WholesaleTrade_WholesaleTrade_LumberAndOtherConstructionMaterialsMerchantWholesalers,
    031E: Male_WholesaleTrade_WholesaleTrade_ProfessionalAndCommercialEquipmentAndSuppliesMerchantWholesalers,
    032E: 'Male_WholesaleTrade_WholesaleTrade_MetalsAndMinerals,ExceptPetroleum,MerchantWholesalers',
    033E: Male_WholesaleTrade_WholesaleTrade_HouseholdAppliancesAndElectricalAndElectronicGoodsMerchantWholesalers,
    034E: 'Male_WholesaleTrade_WholesaleTrade_Hardware,AndPlumbingAndHeatingEquipment,AndSuppliesMerchantWholesalers',
    035E: 'Male_WholesaleTrade_WholesaleTrade_Machinery,Equipment,AndSuppliesMerchantWholesalers',
    036E: Male_WholesaleTrade_WholesaleTrade_RecyclableMaterialMerchantWholesalers,
    037E: Male_WholesaleTrade_WholesaleTrade_MiscellaneousDurableGoodsMerchantWholesalers,
    038E: Male_WholesaleTrade_WholesaleTrade_PaperAndPaperProductsMerchantWholesalers,
    039E: 'Male_WholesaleTrade_WholesaleTrade_Drugs,Sundries,AndChemicalAndAlliedProductsMerchantWholesalers',
    040E: 'Male_WholesaleTrade_WholesaleTrade_Apparel,PieceGoods,AndNotionsMerchantWholesalers',
    041E: Male_WholesaleTrade_WholesaleTrade_GroceryAndRelatedProductMerchantWholesalers,
    042E: Male_WholesaleTrade_WholesaleTrade_FarmProductRawMaterialMerchantWholesalers,
    043E: Male_WholesaleTrade_WholesaleTrade_PetroleumAndPetroleumProductsMerchantWholesalers,
    044E: Male_WholesaleTrade_WholesaleTrade_AlcoholicBeveragesMerchantWholesalers,
    045E: Male_WholesaleTrade_WholesaleTrade_FarmSuppliesMerchantWholesalers, 046E: Male_WholesaleTrade_WholesaleTrade_MiscellaneousNondurableGoodsMerchantWholesalers,
    047E: Male_WholesaleTrade_WholesaleTrade_WholesaleElectronicMarketsAndAgentsAndBrokers,
    049E: Male_RetailTrade_RetailTrade_MotorVehicleAndPartsDealers, 050E: 'Male_RetailTrade_RetailTrade_FurnitureAndHomeFurnishings,AndHouseholdApplianceStores',
    051E: Male_RetailTrade_RetailTrade_ElectronicsStores, 052E: Male_RetailTrade_RetailTrade_BuildingMaterialAndGardenEquipmentAndSuppliesDealers,
    053E: Male_RetailTrade_RetailTrade_FoodAndBeverageStores, 054E: Male_RetailTrade_RetailTrade_PharmaciesAndDrugStores,
    055E: 'Male_RetailTrade_RetailTrade_HealthAndPersonalCare,ExceptDrug,Stores',
    056E: Male_RetailTrade_RetailTrade_GasolineStations, 057E: 'Male_RetailTrade_RetailTrade_ClothingAndAccessories,IncludingShoe,Stores',
    058E: 'Male_RetailTrade_RetailTrade_Jewelry,Luggage,AndLeatherGoodsStores', 059E: 'Male_RetailTrade_RetailTrade_SportingGoods,AndHobbyAndToyStores',
    060E: 'Male_RetailTrade_RetailTrade_Sewing,Needlework,AndPieceGoodsStores', 061E: Male_RetailTrade_RetailTrade_MusicalInstrumentAndSuppliesStores,
    062E: Male_RetailTrade_RetailTrade_BookStoresAndNewsDealers, 063E: Male_RetailTrade_RetailTrade_DepartmentAndOtherGeneralMerchandiseStores,
    064E: Male_RetailTrade_RetailTrade_RetailFlorists, 065E: Male_RetailTrade_RetailTrade_OfficeSuppliesAndStationeryStores,
    066E: 'Male_RetailTrade_RetailTrade_UsedMerchandise,Gift,Novelty,AndSouvenir,AndOtherMiscellaneousStores',
    067E: Male_RetailTrade_RetailTrade_ElectronicShoppingAndMail-orderHouses, 068E: Male_RetailTrade_RetailTrade_VendingMachineOperators,
    069E: Male_RetailTrade_RetailTrade_FuelDealers, 070E: Male_RetailTrade_RetailTrade_OtherDirectSellingEstablishments,
    073E: 'Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_AirTransportation',
    074E: 'Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_RailTransportation',
    075E: 'Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_WaterTransportation',
    076E: 'Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_TruckTransportation',
    077E: 'Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_U.S.PostalService',
    078E: 'Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_OtherTransportation,AndSupportActivities,AndCouriers',
    079E: 'Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_WarehousingAndStorage',
    080E: 'Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing,AndUtilities_Utilities',
    082E: 'Male_Information_Information_Publishing,AndMotionPictureAndSoundRecordingIndustries',
    083E: 'Male_Information_Information_Broadcasting,InternetPublishing,AndTelecommunicationsServices',
    084E: 'Male_Information_Information_DataProcessing,Libraries,AndOtherInformationServices',
    086E: 'Male_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance',
    087E: 'Male_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_RealEstateAndRentalAndLeasing',
    089E: 'Male_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndTechnicalServices',
    090E: 'Male_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_ManagementOfCompaniesAndEnterprises',
    091E: 'Male_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_AdministrativeAndSupportAndWasteManagementServices',
    093E: 'Male_EducationalServices,AndHealthCareAndSocialAssistance_EducationalServices,AndHealthCareAndSocialAssistance_EducationalServices',
    095E: 'Male_EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance_HealthCare',
    096E: 'Male_EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance_SocialAssistance',
    098E: 'Male_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_Arts,Entertainment,AndRecreation',
    099E: 'Male_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_AccommodationAndFoodServices',
    101E: 'Male_OtherServices,ExceptPublicAdministration_OtherServices,ExceptPublicAdministration_RepairAndMaintenance',
    102E: 'Male_OtherServices,ExceptPublicAdministration_OtherServices,ExceptPublicAdministration_PersonalAndLaundryServices',
    103E: 'Male_OtherServices,ExceptPublicAdministration_OtherServices,ExceptPublicAdministration_Religious,Grantmaking,Civic,Professional,AndSimilarOrganizations',
    104E: 'Male_OtherServices,ExceptPublicAdministration_OtherServices,ExceptPublicAdministration_PrivateHouseholds',
    105E: Male_PublicAdministration_PublicAdministration_PublicAdministration, 108E: 'Female_Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting',
    109E: 'Female_Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting,AndMining_Mining,Quarrying,AndOilAndGasExtraction',
    110E: Female_Construction_Construction_Construction, 112E: Female_Manufacturing_Manufacturing_Food,
    113E: Female_Manufacturing_Manufacturing_BeverageAndTobaccoProducts, 114E: Female_Manufacturing_Manufacturing_TextileMillsAndTextileProducts,
    115E: Female_Manufacturing_Manufacturing_Apparel, 116E: Female_Manufacturing_Manufacturing_LeatherAndAlliedProducts,
    117E: Female_Manufacturing_Manufacturing_WoodProducts, 118E: Female_Manufacturing_Manufacturing_Paper,
    119E: Female_Manufacturing_Manufacturing_PrintingAndRelatedSupportActivities,
    120E: Female_Manufacturing_Manufacturing_PetroleumAndCoalProducts, 121E: Female_Manufacturing_Manufacturing_Chemicals,
    122E: Female_Manufacturing_Manufacturing_PlasticsAndRubberProducts, 123E: Female_Manufacturing_Manufacturing_NonmetallicMineralProducts,
    124E: Female_Manufacturing_Manufacturing_MetalAndMetalProducts, 125E: Female_Manufacturing_Manufacturing_Machinery,
    126E: Female_Manufacturing_Manufacturing_ComputerAndElectronicProducts, 127E: 'Female_Manufacturing_Manufacturing_ElectricalEquipment,Appliances,AndComponents',
    128E: Female_Manufacturing_Manufacturing_TransportationEquipment, 129E: Female_Manufacturing_Manufacturing_FurnitureAndRelatedProductManufacturing,
    130E: Female_Manufacturing_Manufacturing_MiscellaneousManufacturing, 132E: Female_WholesaleTrade_WholesaleTrade_MotorVehicleAndMotorVehiclePartsAndSuppliesMerchantWholesalers,
    133E: Female_WholesaleTrade_WholesaleTrade_FurnitureAndHomeFurnishingMerchantWholesalers,
    134E: Female_WholesaleTrade_WholesaleTrade_LumberAndOtherConstructionMaterialsMerchantWholesalers,
    135E: Female_WholesaleTrade_WholesaleTrade_ProfessionalAndCommercialEquipmentAndSuppliesMerchantWholesalers,
    136E: 'Female_WholesaleTrade_WholesaleTrade_MetalsAndMinerals,ExceptPetroleum,MerchantWholesalers',
    137E: Female_WholesaleTrade_WholesaleTrade_HouseholdAppliancesAndElectricalAndElectronicGoodsMerchantWholesalers,
    138E: 'Female_WholesaleTrade_WholesaleTrade_Hardware,AndPlumbingAndHeatingEquipment,AndSuppliesMerchantWholesalers',
    139E: 'Female_WholesaleTrade_WholesaleTrade_Machinery,Equipment,AndSuppliesMerchantWholesalers',
    140E: Female_WholesaleTrade_WholesaleTrade_RecyclableMaterialMerchantWholesalers,
    141E: Female_WholesaleTrade_WholesaleTrade_MiscellaneousDurableGoodsMerchantWholesalers,
    142E: Female_WholesaleTrade_WholesaleTrade_PaperAndPaperProductsMerchantWholesalers,
    143E: 'Female_WholesaleTrade_WholesaleTrade_Drugs,Sundries,AndChemicalAndAlliedProductsMerchantWholesalers',
    144E: 'Female_WholesaleTrade_WholesaleTrade_Apparel,PieceGoods,AndNotionsMerchantWholesalers',
    145E: Female_WholesaleTrade_WholesaleTrade_GroceryAndRelatedProductMerchantWholesalers,
    146E: Female_WholesaleTrade_WholesaleTrade_FarmProductRawMaterialMerchantWholesalers,
    147E: Female_WholesaleTrade_WholesaleTrade_PetroleumAndPetroleumProductsMerchantWholesalers,
    148E: Female_WholesaleTrade_WholesaleTrade_AlcoholicBeveragesMerchantWholesalers,
    149E: Female_WholesaleTrade_WholesaleTrade_FarmSuppliesMerchantWholesalers, 150E: Female_WholesaleTrade_WholesaleTrade_MiscellaneousNondurableGoodsMerchantWholesalers,
    151E: Female_WholesaleTrade_WholesaleTrade_WholesaleElectronicMarketsAndAgentsAndBrokers,
    153E: Female_RetailTrade_RetailTrade_MotorVehicleAndPartsDealers, 154E: 'Female_RetailTrade_RetailTrade_FurnitureAndHomeFurnishings,AndHouseholdApplianceStores',
    155E: Female_RetailTrade_RetailTrade_ElectronicsStores, 156E: Female_RetailTrade_RetailTrade_BuildingMaterialAndGardenEquipmentAndSuppliesDealers,
    157E: Female_RetailTrade_RetailTrade_FoodAndBeverageStores, 158E: Female_RetailTrade_RetailTrade_PharmaciesAndDrugStores,
    159E: 'Female_RetailTrade_RetailTrade_HealthAndPersonalCare,ExceptDrug,Stores',
    160E: Female_RetailTrade_RetailTrade_GasolineStations, 161E: 'Female_RetailTrade_RetailTrade_ClothingAndAccessories,IncludingShoe,Stores',
    162E: 'Female_RetailTrade_RetailTrade_Jewelry,Luggage,AndLeatherGoodsStores',
    163E: 'Female_RetailTrade_RetailTrade_SportingGoods,AndHobbyAndToyStores', 164E: 'Female_RetailTrade_RetailTrade_Sewing,Needlework,AndPieceGoodsStores',
    165E: Female_RetailTrade_RetailTrade_MusicalInstrumentAndSuppliesStores, 166E: Female_RetailTrade_RetailTrade_BookStoresAndNewsDealers,
    167E: Female_RetailTrade_RetailTrade_DepartmentAndOtherGeneralMerchandiseStores,
    168E: Female_RetailTrade_RetailTrade_RetailFlorists, 169E: Female_RetailTrade_RetailTrade_OfficeSuppliesAndStationeryStores,
    170E: 'Female_RetailTrade_RetailTrade_UsedMerchandise,Gift,Novelty,AndSouvenir,AndOtherMiscellaneousStores',
    171E: Female_RetailTrade_RetailTrade_ElectronicShoppingAndMail-orderHouses, 172E: Female_RetailTrade_RetailTrade_VendingMachineOperators,
    173E: Female_RetailTrade_RetailTrade_FuelDealers, 174E: Female_RetailTrade_RetailTrade_OtherDirectSellingEstablishments,
    177E: 'Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_AirTransportation',
    178E: 'Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_RailTransportation',
    179E: 'Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_WaterTransportation',
    180E: 'Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_TruckTransportation',
    181E: 'Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_U.S.PostalService',
    182E: 'Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_OtherTransportation,AndSupportActivities,AndCouriers',
    183E: 'Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_WarehousingAndStorage',
    184E: 'Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing,AndUtilities_Utilities',
    186E: 'Female_Information_Information_Publishing,AndMotionPictureAndSoundRecordingIndustries',
    187E: 'Female_Information_Information_Broadcasting,InternetPublishing,AndTelecommunicationsServices',
    188E: 'Female_Information_Information_DataProcessing,Libraries,AndOtherInformationServices',
    190E: 'Female_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance',
    191E: 'Female_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_RealEstateAndRentalAndLeasing',
    193E: 'Female_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndTechnicalServices',
    194E: 'Female_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_ManagementOfCompaniesAndEnterprises',
    195E: 'Female_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_AdministrativeAndSupportAndWasteManagementServices',
    197E: 'Female_EducationalServices,AndHealthCareAndSocialAssistance_EducationalServices,AndHealthCareAndSocialAssistance_EducationalServices',
    199E: 'Female_EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance_HealthCare',
    200E: 'Female_EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance_SocialAssistance',
    202E: 'Female_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_Arts,Entertainment,AndRecreation',
    203E: 'Female_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_AccommodationAndFoodServices',
    205E: 'Female_OtherServices,ExceptPublicAdministration_OtherServices,ExceptPublicAdministration_RepairAndMaintenance',
    206E: 'Female_OtherServices,ExceptPublicAdministration_OtherServices,ExceptPublicAdministration_PersonalAndLaundryServices',
    207E: 'Female_OtherServices,ExceptPublicAdministration_OtherServices,ExceptPublicAdministration_Religious,Grantmaking,Civic,Professional,AndSimilarOrganizations',
    208E: 'Female_OtherServices,ExceptPublicAdministration_OtherServices,ExceptPublicAdministration_PrivateHouseholds',
    209E: Female_PublicAdministration_PublicAdministration_PublicAdministration}
  dimension_labels: [sex, 'industry::group', 'industry::subgroup', 'industry::industry']
  id: B24030
  value_label: industry_population
max_year: 2017
min_year: 2009
name: acs_ygsi_sex_by_industry
tag: acs
calc_rca: True
