name: "acs_ygo_occupation_for_median_earnings"
tag: "acs"
min_year: 2012
max_year: 2017
acs_table:
    id: "B24011"
    value_label: "occupation_median_earnings"
    dimension_labels: [
        "occupation::group",
        "occupation::subgroup",
        "occupation::occupation",
    ]
    columns:
        004: "Management,Business,Science,AndArtsOccupations_Management,Business,AndFinancialOccupations_ManagementOccupations"
        005: "Management,Business,Science,AndArtsOccupations_Management,Business,AndFinancialOccupations_BusinessAndFinancialOperationsOccupations"
        007: "Management,Business,Science,AndArtsOccupations_Computer,Engineering,AndScienceOccupations_ComputerAndMathematicalOccupations"
        008: "Management,Business,Science,AndArtsOccupations_Computer,Engineering,AndScienceOccupations_ArchitectureAndEngineeringOccupations"
        009: "Management,Business,Science,AndArtsOccupations_Computer,Engineering,AndScienceOccupations_Life,Physical,AndSocialScienceOccupations"
        011: "Management,Business,Science,AndArtsOccupations_Education,Legal,CommunityService,Arts,AndMediaOccupations_CommunityAndSocialServiceOccupations"
        012: "Management,Business,Science,AndArtsOccupations_Education,Legal,CommunityService,Arts,AndMediaOccupations_LegalOccupations"
        013: "Management,Business,Science,AndArtsOccupations_Education,Legal,CommunityService,Arts,AndMediaOccupations_Education,Training,AndLibraryOccupations"
        014: "Management,Business,Science,AndArtsOccupations_Education,Legal,CommunityService,Arts,AndMediaOccupations_Arts,Design,Entertainment,Sports,AndMediaOccupations"
        016: "Management,Business,Science,AndArtsOccupations_HealthcarePractitionersAndTechnicalOccupations_HealthDiagnosingAndTreatingPractitionersAndOtherTechnicalOccupations"
        017: "Management,Business,Science,AndArtsOccupations_HealthcarePractitionersAndTechnicalOccupations_HealthTechnologistsAndTechnicians"
        019: "ServiceOccupations_ServiceOccupations_HealthcareSupportOccupations"
        021: "ServiceOccupations_ProtectiveServiceOccupations_FireFightingAndPrevention,AndOtherProtectiveServiceWorkersIncludingSupervisors"
        022: "ServiceOccupations_ProtectiveServiceOccupations_LawEnforcementWorkersIncludingSupervisors"
        023: "ServiceOccupations_ServiceOccupations_FoodPreparationAndServingRelatedOccupations"
        024: "ServiceOccupations_ServiceOccupations_BuildingAndGroundsCleaningAndMaintenanceOccupations"
        025: "ServiceOccupations_ServiceOccupations_PersonalCareAndServiceOccupations"
        027: "SalesAndOfficeOccupations_SalesAndOfficeOccupations_SalesAndRelatedOccupations"
        028: "SalesAndOfficeOccupations_SalesAndOfficeOccupations_OfficeAndAdministrativeSupportOccupations"
        030: "NaturalResources,Construction,AndMaintenanceOccupations_NaturalResources,Construction,AndMaintenanceOccupations_Farming,Fishing,AndForestryOccupations"
        031: "NaturalResources,Construction,AndMaintenanceOccupations_NaturalResources,Construction,AndMaintenanceOccupations_ConstructionAndExtractionOccupations"
        032: "NaturalResources,Construction,AndMaintenanceOccupations_NaturalResources,Construction,AndMaintenanceOccupations_Installation,Maintenance,AndRepairOccupations"
        034: "Production,Transportation,AndMaterialMovingOccupations_Production,Transportation,AndMaterialMovingOccupations_ProductionOccupations"
        035: "Production,Transportation,AndMaterialMovingOccupations_Production,Transportation,AndMaterialMovingOccupations_TransportationOccupations"
        036: "Production,Transportation,AndMaterialMovingOccupations_Production,Transportation,AndMaterialMovingOccupations_MaterialMovingOccupations"


