name: "acs_ygsi_sex_by_industry"
tag: "acs"
min_year: 2009
max_year: 2017
acs_table:
    id: "B24030"
    value_label: "industry_population"
    dimension_labels: [
        "sex",
        "industry::group",
        "industry::subgroup",
        "industry::industry",
    ]
    columns:
        004: "Male_Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting"
        005: "Male_Agriculture,Forestry,FishingAndHunting,AndMining_Mining,Quarrying,AndOilAndGasExtraction"
        006: "Male_Construction"
        008: "Male_Manufacturing_Food"
        009: "Male_Manufacturing_BeverageAndTobaccoProducts"
        010: "Male_Manufacturing_TextileMillsAndTextileProducts"
        011: "Male_Manufacturing_Apparel"
        012: "Male_Manufacturing_LeatherAndAlliedProducts"
        013: "Male_Manufacturing_WoodProducts"
        014: "Male_Manufacturing_Paper"
        015: "Male_Manufacturing_PrintingAndRelatedSupportActivities"
        016: "Male_Manufacturing_PetroleumAndCoalProducts"
        017: "Male_Manufacturing_Chemicals"
        018: "Male_Manufacturing_PlasticsAndRubberProducts"
        019: "Male_Manufacturing_NonmetallicMineralProducts"
        020: "Male_Manufacturing_MetalAndMetalProducts"
        021: "Male_Manufacturing_Machinery"
        022: "Male_Manufacturing_ComputerAndElectronicProducts"
        023: "Male_Manufacturing_ElectricalEquipment,Appliances,AndComponents"
        024: "Male_Manufacturing_TransportationEquipment"
        025: "Male_Manufacturing_FurnitureAndRelatedProductManufacturing"
        026: "Male_Manufacturing_MiscellaneousManufacturing"
        028: "Male_WholesaleTrade_MotorVehicleAndMotorVehiclePartsAndSuppliesMerchantWholesalers"
        029: "Male_WholesaleTrade_FurnitureAndHomeFurnishingMerchantWholesalers"
        030: "Male_WholesaleTrade_LumberAndOtherConstructionMaterialsMerchantWholesalers"
        031: "Male_WholesaleTrade_ProfessionalAndCommercialEquipmentAndSuppliesMerchantWholesalers"
        032: "Male_WholesaleTrade_MetalsAndMinerals,ExceptPetroleum,MerchantWholesalers"
        033: "Male_WholesaleTrade_HouseholdAppliancesAndElectricalAndElectronicGoodsMerchantWholesalers"
        034: "Male_WholesaleTrade_Hardware,AndPlumbingAndHeatingEquipment,AndSuppliesMerchantWholesalers"
        035: "Male_WholesaleTrade_Machinery,Equipment,AndSuppliesMerchantWholesalers"
        036: "Male_WholesaleTrade_RecyclableMaterialMerchantWholesalers"
        037: "Male_WholesaleTrade_MiscellaneousDurableGoodsMerchantWholesalers"
        038: "Male_WholesaleTrade_PaperAndPaperProductsMerchantWholesalers"
        039: "Male_WholesaleTrade_Drugs,Sundries,AndChemicalAndAlliedProductsMerchantWholesalers"
        040: "Male_WholesaleTrade_Apparel,PieceGoods,AndNotionsMerchantWholesalers"
        041: "Male_WholesaleTrade_GroceryAndRelatedProductMerchantWholesalers"
        042: "Male_WholesaleTrade_FarmProductRawMaterialMerchantWholesalers"
        043: "Male_WholesaleTrade_PetroleumAndPetroleumProductsMerchantWholesalers"
        044: "Male_WholesaleTrade_AlcoholicBeveragesMerchantWholesalers"
        045: "Male_WholesaleTrade_FarmSuppliesMerchantWholesalers"
        046: "Male_WholesaleTrade_MiscellaneousNondurableGoodsMerchantWholesalers"
        047: "Male_WholesaleTrade_WholesaleElectronicMarketsAndAgentsAndBrokers"
        049: "Male_RetailTrade_MotorVehicleAndPartsDealers"
        050: "Male_RetailTrade_FurnitureAndHomeFurnishings,AndHouseholdApplianceStores"
        051: "Male_RetailTrade_ElectronicsStores"
        052: "Male_RetailTrade_BuildingMaterialAndGardenEquipmentAndSuppliesDealers"
        053: "Male_RetailTrade_FoodAndBeverageStores"
        054: "Male_RetailTrade_PharmaciesAndDrugStores"
        055: "Male_RetailTrade_HealthAndPersonalCare,ExceptDrug,Stores"
        056: "Male_RetailTrade_GasolineStations"
        057: "Male_RetailTrade_ClothingAndAccessories,IncludingShoe,Stores"
        058: "Male_RetailTrade_Jewelry,Luggage,AndLeatherGoodsStores"
        059: "Male_RetailTrade_SportingGoods,AndHobbyAndToyStores"
        060: "Male_RetailTrade_Sewing,Needlework,AndPieceGoodsStores"
        061: "Male_RetailTrade_MusicalInstrumentAndSuppliesStores"
        062: "Male_RetailTrade_BookStoresAndNewsDealers"
        063: "Male_RetailTrade_DepartmentAndOtherGeneralMerchandiseStores"
        064: "Male_RetailTrade_RetailFlorists"
        065: "Male_RetailTrade_OfficeSuppliesAndStationeryStores"
        066: "Male_RetailTrade_UsedMerchandise,Gift,Novelty,AndSouvenir,AndOtherMiscellaneousStores"
        067: "Male_RetailTrade_ElectronicShoppingAndMail-orderHouses"
        068: "Male_RetailTrade_VendingMachineOperators"
        069: "Male_RetailTrade_FuelDealers"
        070: "Male_RetailTrade_OtherDirectSellingEstablishments"
        073: "Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_AirTransportation"
        074: "Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_RailTransportation"
        075: "Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_WaterTransportation"
        076: "Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_TruckTransportation"
        077: "Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_U.S.PostalService"
        078: "Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_OtherTransportation,AndSupportActivities,AndCouriers"
        079: "Male_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_WarehousingAndStorage"
        080: "Male_TransportationAndWarehousing,AndUtilities_Utilities"
        082: "Male_Information_Publishing,AndMotionPictureAndSoundRecordingIndustries"
        083: "Male_Information_Broadcasting,InternetPublishing,AndTelecommunicationsServices"
        084: "Male_Information_DataProcessing,Libraries,AndOtherInformationServices"
        086: "Male_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance"
        087: "Male_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_RealEstateAndRentalAndLeasing"
        089: "Male_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndTechnicalServices"
        090: "Male_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_ManagementOfCompaniesAndEnterprises"
        091: "Male_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_AdministrativeAndSupportAndWasteManagementServices"
        093: "Male_EducationalServices,AndHealthCareAndSocialAssistance_EducationalServices"
        095: "Male_EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance_HealthCare"
        096: "Male_EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance_SocialAssistance"
        098: "Male_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_Arts,Entertainment,AndRecreation"
        099: "Male_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_AccommodationAndFoodServices"
        101: "Male_OtherServices,ExceptPublicAdministration_RepairAndMaintenance"
        102: "Male_OtherServices,ExceptPublicAdministration_PersonalAndLaundryServices"
        103: "Male_OtherServices,ExceptPublicAdministration_Religious,Grantmaking,Civic,Professional,AndSimilarOrganizations"
        104: "Male_OtherServices,ExceptPublicAdministration_PrivateHouseholds"
        105: "Male_PublicAdministration"
        108: "Female_Agriculture,Forestry,FishingAndHunting,AndMining_Agriculture,Forestry,FishingAndHunting"
        109: "Female_Agriculture,Forestry,FishingAndHunting,AndMining_Mining,Quarrying,AndOilAndGasExtraction"
        110: "Female_Construction"
        112: "Female_Manufacturing_Food"
        113: "Female_Manufacturing_BeverageAndTobaccoProducts"
        114: "Female_Manufacturing_TextileMillsAndTextileProducts"
        115: "Female_Manufacturing_Apparel"
        116: "Female_Manufacturing_LeatherAndAlliedProducts"
        117: "Female_Manufacturing_WoodProducts"
        118: "Female_Manufacturing_Paper"
        119: "Female_Manufacturing_PrintingAndRelatedSupportActivities"
        120: "Female_Manufacturing_PetroleumAndCoalProducts"
        121: "Female_Manufacturing_Chemicals"
        122: "Female_Manufacturing_PlasticsAndRubberProducts"
        123: "Female_Manufacturing_NonmetallicMineralProducts"
        124: "Female_Manufacturing_MetalAndMetalProducts"
        125: "Female_Manufacturing_Machinery"
        126: "Female_Manufacturing_ComputerAndElectronicProducts"
        127: "Female_Manufacturing_ElectricalEquipment,Appliances,AndComponents"
        128: "Female_Manufacturing_TransportationEquipment"
        129: "Female_Manufacturing_FurnitureAndRelatedProductManufacturing"
        130: "Female_Manufacturing_MiscellaneousManufacturing"
        132: "Female_WholesaleTrade_MotorVehicleAndMotorVehiclePartsAndSuppliesMerchantWholesalers"
        133: "Female_WholesaleTrade_FurnitureAndHomeFurnishingMerchantWholesalers"
        134: "Female_WholesaleTrade_LumberAndOtherConstructionMaterialsMerchantWholesalers"
        135: "Female_WholesaleTrade_ProfessionalAndCommercialEquipmentAndSuppliesMerchantWholesalers"
        136: "Female_WholesaleTrade_MetalsAndMinerals,ExceptPetroleum,MerchantWholesalers"
        137: "Female_WholesaleTrade_HouseholdAppliancesAndElectricalAndElectronicGoodsMerchantWholesalers"
        138: "Female_WholesaleTrade_Hardware,AndPlumbingAndHeatingEquipment,AndSuppliesMerchantWholesalers"
        139: "Female_WholesaleTrade_Machinery,Equipment,AndSuppliesMerchantWholesalers"
        140: "Female_WholesaleTrade_RecyclableMaterialMerchantWholesalers"
        141: "Female_WholesaleTrade_MiscellaneousDurableGoodsMerchantWholesalers"
        142: "Female_WholesaleTrade_PaperAndPaperProductsMerchantWholesalers"
        143: "Female_WholesaleTrade_Drugs,Sundries,AndChemicalAndAlliedProductsMerchantWholesalers"
        144: "Female_WholesaleTrade_Apparel,PieceGoods,AndNotionsMerchantWholesalers"
        145: "Female_WholesaleTrade_GroceryAndRelatedProductMerchantWholesalers"
        146: "Female_WholesaleTrade_FarmProductRawMaterialMerchantWholesalers"
        147: "Female_WholesaleTrade_PetroleumAndPetroleumProductsMerchantWholesalers"
        148: "Female_WholesaleTrade_AlcoholicBeveragesMerchantWholesalers"
        149: "Female_WholesaleTrade_FarmSuppliesMerchantWholesalers"
        150: "Female_WholesaleTrade_MiscellaneousNondurableGoodsMerchantWholesalers"
        151: "Female_WholesaleTrade_WholesaleElectronicMarketsAndAgentsAndBrokers"
        153: "Female_RetailTrade_MotorVehicleAndPartsDealers"
        154: "Female_RetailTrade_FurnitureAndHomeFurnishings,AndHouseholdApplianceStores"
        155: "Female_RetailTrade_ElectronicsStores"
        156: "Female_RetailTrade_BuildingMaterialAndGardenEquipmentAndSuppliesDealers"
        157: "Female_RetailTrade_FoodAndBeverageStores"
        158: "Female_RetailTrade_PharmaciesAndDrugStores"
        159: "Female_RetailTrade_HealthAndPersonalCare,ExceptDrug,Stores"
        160: "Female_RetailTrade_GasolineStations"
        161: "Female_RetailTrade_ClothingAndAccessories,IncludingShoe,Stores"
        162: "Female_RetailTrade_Jewelry,Luggage,AndLeatherGoodsStores"
        163: "Female_RetailTrade_SportingGoods,AndHobbyAndToyStores"
        164: "Female_RetailTrade_Sewing,Needlework,AndPieceGoodsStores"
        165: "Female_RetailTrade_MusicalInstrumentAndSuppliesStores"
        166: "Female_RetailTrade_BookStoresAndNewsDealers"
        167: "Female_RetailTrade_DepartmentAndOtherGeneralMerchandiseStores"
        168: "Female_RetailTrade_RetailFlorists"
        169: "Female_RetailTrade_OfficeSuppliesAndStationeryStores"
        170: "Female_RetailTrade_UsedMerchandise,Gift,Novelty,AndSouvenir,AndOtherMiscellaneousStores"
        171: "Female_RetailTrade_ElectronicShoppingAndMail-orderHouses"
        172: "Female_RetailTrade_VendingMachineOperators"
        173: "Female_RetailTrade_FuelDealers"
        174: "Female_RetailTrade_OtherDirectSellingEstablishments"
        177: "Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_AirTransportation"
        178: "Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_RailTransportation"
        179: "Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_WaterTransportation"
        180: "Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_TruckTransportation"
        181: "Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_U.S.PostalService"
        182: "Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_OtherTransportation,AndSupportActivities,AndCouriers"
        183: "Female_TransportationAndWarehousing,AndUtilities_TransportationAndWarehousing_WarehousingAndStorage"
        184: "Female_TransportationAndWarehousing,AndUtilities_Utilities"
        186: "Female_Information_Publishing,AndMotionPictureAndSoundRecordingIndustries"
        187: "Female_Information_Broadcasting,InternetPublishing,AndTelecommunicationsServices"
        188: "Female_Information_DataProcessing,Libraries,AndOtherInformationServices"
        190: "Female_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_FinanceAndInsurance"
        191: "Female_FinanceAndInsurance,AndRealEstateAndRentalAndLeasing_RealEstateAndRentalAndLeasing"
        193: "Female_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_Professional,Scientific,AndTechnicalServices"
        194: "Female_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_ManagementOfCompaniesAndEnterprises"
        195: "Female_Professional,Scientific,AndManagement,AndAdministrativeAndWasteManagementServices_AdministrativeAndSupportAndWasteManagementServices"
        197: "Female_EducationalServices,AndHealthCareAndSocialAssistance_EducationalServices"
        199: "Female_EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance_HealthCare"
        200: "Female_EducationalServices,AndHealthCareAndSocialAssistance_HealthCareAndSocialAssistance_SocialAssistance"
        202: "Female_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_Arts,Entertainment,AndRecreation"
        203: "Female_Arts,Entertainment,AndRecreation,AndAccommodationAndFoodServices_AccommodationAndFoodServices"
        205: "Female_OtherServices,ExceptPublicAdministration_RepairAndMaintenance"
        206: "Female_OtherServices,ExceptPublicAdministration_PersonalAndLaundryServices"
        207: "Female_OtherServices,ExceptPublicAdministration_Religious,Grantmaking,Civic,Professional,AndSimilarOrganizations"
        208: "Female_OtherServices,ExceptPublicAdministration_PrivateHouseholds"
        209: "Female_PublicAdministration"
