name: "acs_yghsa_health_insurance_coverage_status_by_sex_by_age"
tag: "acs"
min_year: 2012
max_year: 2017
acs_table:
    id: "B27001"
    value_label: "health_insurance_coverage_population"
    dimension_labels: [
        "sex",
        "age",
        "health_insurance_status",
    ]
    columns:
        004E: "Male_Under6Years_WithHealthInsuranceCoverage"
        005E: "Male_Under6Years_NoHealthInsuranceCoverage"
        007E: "Male_6To17Years_WithHealthInsuranceCoverage"
        008E: "Male_6To17Years_NoHealthInsuranceCoverage"
        010E: "Male_18To24Years_WithHealthInsuranceCoverage"
        011E: "Male_18To24Years_NoHealthInsuranceCoverage"
        013E: "Male_25To34Years_WithHealthInsuranceCoverage"
        014E: "Male_25To34Years_NoHealthInsuranceCoverage"
        016E: "Male_35To44Years_WithHealthInsuranceCoverage"
        017E: "Male_35To44Years_NoHealthInsuranceCoverage"
        019E: "Male_45To54Years_WithHealthInsuranceCoverage"
        020E: "Male_45To54Years_NoHealthInsuranceCoverage"
        022E: "Male_55To64Years_WithHealthInsuranceCoverage"
        023E: "Male_55To64Years_NoHealthInsuranceCoverage"
        025E: "Male_65To74Years_WithHealthInsuranceCoverage"
        026E: "Male_65To74Years_NoHealthInsuranceCoverage"
        028E: "Male_75YearsAndOver_WithHealthInsuranceCoverage"
        029E: "Male_75YearsAndOver_NoHealthInsuranceCoverage"
        032E: "Female_Under6Years_WithHealthInsuranceCoverage"
        033E: "Female_Under6Years_NoHealthInsuranceCoverage"
        035E: "Female_6To17Years_WithHealthInsuranceCoverage"
        036E: "Female_6To17Years_NoHealthInsuranceCoverage"
        038E: "Female_18To24Years_WithHealthInsuranceCoverage"
        039E: "Female_18To24Years_NoHealthInsuranceCoverage"
        041E: "Female_25To34Years_WithHealthInsuranceCoverage"
        042E: "Female_25To34Years_NoHealthInsuranceCoverage"
        044E: "Female_35To44Years_WithHealthInsuranceCoverage"
        045E: "Female_35To44Years_NoHealthInsuranceCoverage"
        047E: "Female_45To54Years_WithHealthInsuranceCoverage"
        048E: "Female_45To54Years_NoHealthInsuranceCoverage"
        050E: "Female_55To64Years_WithHealthInsuranceCoverage"
        051E: "Female_55To64Years_NoHealthInsuranceCoverage"
        053E: "Female_65To74Years_WithHealthInsuranceCoverage"
        054E: "Female_65To74Years_NoHealthInsuranceCoverage"
        056E: "Female_75YearsAndOver_WithHealthInsuranceCoverage"
        057E: "Female_75YearsAndOver_NoHealthInsuranceCoverage"


