name: "acs_ygpsar_poverty_by_sex_age_race"
tag: "acs"
race_tag: "white_alone"
min_year: 2009
max_year: 2017
acs_table:
    id: "B17001A"
    value_label: "population"
    dimension_labels: [
        "poverty_status", "sex", "age"
    ]
    columns:
        004E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_Under5Years"
        005E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_5Years"
        006E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_6To11Years"
        007E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_12To14Years"
        008E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_15Years"
        009E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_16And17Years"
        010E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_18To24Years"
        011E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_25To34Years"
        012E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_35To44Years"
        013E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_45To54Years"
        014E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_55To64Years"
        015E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_65To74Years"
        016E: "IncomeInThePast12MonthsBelowPovertyLevel_Male_75YearsAndOver"
        018E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_Under5Years"
        019E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_5Years"
        020E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_6To11Years"
        021E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_12To14Years"
        022E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_15Years"
        023E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_16And17Years"
        024E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_18To24Years"
        025E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_25To34Years"
        026E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_35To44Years"
        027E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_45To54Years"
        028E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_55To64Years"
        029E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_65To74Years"
        030E: "IncomeInThePast12MonthsBelowPovertyLevel_Female_75YearsAndOver"
        033E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_Under5Years"
        034E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_5Years"
        035E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_6To11Years"
        036E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_12To14Years"
        037E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_15Years"
        038E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_16And17Years"
        039E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_18To24Years"
        040E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_25To34Years"
        041E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_35To44Years"
        042E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_45To54Years"
        043E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_55To64Years"
        044E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_65To74Years"
        045E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Male_75YearsAndOver"
        047E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_Under5Years"
        048E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_5Years"
        049E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_6To11Years"
        050E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_12To14Years"
        051E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_15Years"
        052E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_16And17Years"
        053E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_18To24Years"
        054E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_25To34Years"
        055E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_35To44Years"
        056E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_45To54Years"
        057E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_55To64Years"
        058E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_65To74Years"
        059E: "IncomeInThePast12MonthsAtOrAbovePovertyLevel_Female_75YearsAndOver"

